/* eslint-disable no-multi-str */
// This file basically contains the text in Spanish and in English and is used as a dictionary to use in the copy text all around the project. Please refer to this document as "THE GOSPEL";

const HomepageText = [
  {
    en: 'Quality home services, on demand',
    sp: 'Servicios a domicilio de calidad, bajo demanda',
  },
  {
    en: "Direct Connection \
          Yazta is not a middleman. Yazta is a \
          marketplace where Clients can \
          connect with Pro's DIRECTLY. On Yazta you \
          can search among all the Pro's \
          available in your area and choose the ones \
          you'd like to contact. Use \
          your needs as search criteria. Live-in or \
          Temporary, full-time or just \
          in the morning; cleaning, babysitting, cooking \
          or full-service - Yazta \
          will help you find the Pro's you need based on \
          their skills and \
          availability. \
          \n \
          \n \
          Transparency \
          On Yazta making an Offer is super easy and \
          simple. You can send an Offer \
          to the Pro you've selected using Yazta Make \
          an Offer functionality. \
          Contact multiple Pros and negotiate \
          DIRECTLY using Yazta Messaging \
          system. You decide and negotiate your terms \
          - live-in or temporary, how \
          much it will cost, just one-off or recurring, \
          how to pay your Pro - \
          Yazta Offers are built around your needs. \
          Modifying or cancelling a \
          Yazta Offer is simple, free and no strings \
          attached. Try it and see how \
          life gets easier. \
          \n \
          \n \
          Reliability & Trust \
          On Yazta marketplace trust is generated by \
          all users who use the \
          platform. Yazta Feedback functionality \
          makes evaluation and \
          recommendation of Pros and Clients reliable \
          and transparent selection \
          criteria. We've suggested relevant criteria for \
          evaluation and have left \
          an opportunity to all Clients to write \
          recommendations that reflect \
          their experiences with the Pros. When \
          selecting or making an Offer you \
          can consult the evaluation score of your Pro \
          and read what other Clients \
          have shared in terms of recommendations. \
          Additionally all Pros are \
          encouraged to share their work history and \
          past experiences in order to \
          receive offers. And of course, you can \
          always, always, always, write to \
          us using Yazta Support and we will help you \
          solve any issue.",
    sp: 'Conexión Directa \
          Yazta no es un intermediario. Yazta es una \
          plataforma abierta donde los \
          Clientes pueden conectarse con las \
          empleadas domésticas – Yazta Pros \
          - DIRECTAMENTE. En Yazta puedes buscar \
          entre todos las Pro disponibles \
          en tu zona y elegir con las que te gustaría \
          contactar. Utilice sus \
          necesidades como criterio de búsqueda. De \
          Planta o Entrada para Salida, \
          a tiempo completo o solo por la mañana; \
          limpieza, cuidado de niños, \
          cocina o servicio completo: Yazta te ayudará \
          a encontrar las Pros que \
          necesita según sus habilidades y \
          disponibilidad. \
          \n \
          \n \
          Transparencia \
          En Yazta hacer una oferta es súper fácil y \
          simple. Puedes enviar una \
          Oferta al Pro que has seleccionado \
          utilizando la función Oferta Yazta. \
          Ponte en contacto con varios profesionales y \
          negocie DIRECTAMENTE \
          utilizando el sistema de mensajería Yazta. Tu \
          decides y negocias tus \
          términos - De Planta o Entrada para Salida, \
          cuánto costará, solo una \
          vez o recurrente, cómo pagar a tu Pro - las \
          Ofertas de Yazta se basan \
          en sus necesidades. Modificar o cancelar \
          una Oferta de Yazta es simple, \
          gratuito y sin condiciones. Pruébalo y verás \
          cómo la vida se vuelve \
          más fácil. \
          \n \
          \n \
          Fiabilidad y Confianza \
          La confianza en Yazta la generan todos los \
          usuarios que utilizan la \
          plataforma. La Retroalimentación de Yazta \
          hace que la evaluación y la \
          recomendación de Pros y Clientes sean \
          criterios de selección \
          confiables y transparentes. Hemos sugerido \
          criterios relevantes para la \
          evaluación y hemos dejado la oportunidad a \
          todos los Clientes de \
          escribir recomendaciones que reflejen sus \
          experiencias con las Pros. Al \
          seleccionar o hacer una Oferta, puede \
          consultar el puntaje de \
          evaluación de su Pro y leer lo que otros \
          Clientes han compartido como \
          recomendaciones. Además, se alienta a \
          todos las Pros a compartir su \
          historial laboral y experiencias pasadas para \
          recibir ofertas. Y \
          obviamente, siempre, siempre siempre, nos \
          puedes escribir a nosotros en \
          Yazta Support para resolver cualquier duda.',
  },
];

export default HomepageText;
